CREATE DATABASE J6Exam;
GO
USE J6Exam;
GO
CREATE TABLE Product (
    Id NVARCHAR(10) NOT NULL PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Image NVARCHAR(100) NOT NULL,
    Price FLOAT NOT NULL
);